### ISSUE TITLE
invalid character indexing

### ISSUE THREAD

**Issue by hummuscience** [ZJUFanLab/scCATCH#14]
I have a seurat object with approx 100k cells, these are my settings for running the function:

```
clu_markers <- findmarkergenes(combined,
                               species = "Mouse",
                               cluster = c("0","23","21"),
                               match_CellMatch = TRUE,
                               cancer = NULL,
                               tissue = c("Blood","Brain","Spinal cord"),
                               cell_min_pct = 0.25,
                               logfc = 0.25,
                               pvalue = 0.05)
```

And this is the output:

```
Note: the new data matrix includes 98465 cells and 22161 genes. 

Note: there are 3776 potential marker genes in CellMatch database for Mouse on Blood, Brain, Spinal cord. 

Finding potential marker genes for cluster 0 
***Done*** 
Finding potential marker genes for cluster 21 
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing
```

I ran it before with an additional cluster "5" in the vector and it did the same thing (after running cluster 0 successfully). So I thought it is something about cluster 5 and removed it from the list and re-ran. Now it is not working for cluster 21 so I am figuring this is another general issue.

**Comment by hummuscience** [comment]
I got the error also when I set one cluster only:

```
clu_markers0 <- findmarkergenes(combined,
                               species = "Mouse",
                               cluster = '21',
                               match_CellMatch = TRUE,
                               cancer = NULL,
                               tissue = c("Blood","Brain"),
                               cell_min_pct = 0.25,
                               logfc = 0.25,
                               pvalue = 0.05)
```

**Comment by ZJUFanLab** [comment]
Hello, I have no idea about the `Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing` since ` intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE)` don't match the related codes in the `findmarkergenes`. Maybe you can send the Seurat object to Xin Shao(xin_shao@zju.edu.cn) for help to figure it out, he will check the code line by line based on your data. As your data is too large, you can send a part of data by deceasing the gene number, like a 100k cells*100 genes instead of the raw 100k cell-gene matrix.

**Comment by multitalk** [comment]
Hello, I have fix the bug you meet, you can try it now. Thanks!
