### ISSUE TITLE
file too large?

### ISSUE THREAD

**Issue by wfma** [ZJUFanLab/scCATCH#15]
Hello! I am attempting to use scCATCH on an integrated seurat object that has 7 samples. When I do, I get the following message:

```
clu_markers <- findmarkergenes(object = SEURATOBJECT,
                               species = 'Human',
                               cluster = 'All',
                               match_CellMatch = TRUE,
                               cancer = NULL,
                               tissue = "Bronchoalveolar system",
                               cell_min_pct = 0.15,
                               logfc = 0.15,
                               pvalue = 0.05)
```

I was running this on a computing cluster on RStudio, with a requested memory of 125gb. The suerat object was only 4gb in size.

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

Any suggestions?

**Comment by multitalk** [comment]
Hello, you can try to select one cluster for `findmarkergenes`
```
clu_markers <- findmarkergenes(object = SEURATOBJECT,
                               species = 'Human',
                               cluster = '1',
                               match_CellMatch = TRUE,
                               cancer = NULL,
                               tissue = "Bronchoalveolar system",
                               cell_min_pct = 0.15,
                               logfc = 0.15,
                               pvalue = 0.05)
```
If the same error occurs, maybe it's because your integrated Seurat object has a large number of cells and genes. Or you can use the `FindAllMarkers` in Seurat to get a marker gene data.frame and annotate it with `scCATCH` in scCATCH.
```
clu_markers<- FindAllMarkers(SEURATOBJECT)
clu_ann<- scCATCH(clu_markers, species = 'Human', tissue = "Bronchoalveolar system")
```

By the way, if you still want to use the `findmarkergenes` to find the marker genes, maybe you should get more system memory as `findmarkergenes` compares each gene's expression level in one cluster with every other clusters, which indeed requires large memory. 

Good luck!

**Comment by wfma** [comment]
Thank you so much! I understand, I will try that and close the issue for now.
Wei
