### ISSUE TITLE
Workflow with SCTransfrom

### ISSUE THREAD

**Issue by jhb1980** [ZJUFanLab/scCATCH#7]
Would scCATCH work on a Seurat object that was normalized using SCtransform?

I've been waiting for a cluster-based annotation so long! Thank you for developing a great tool!

**Comment by ZJUFanLab** [comment]
Hello, scCATCH also works on a Seurat object normalized using SCtransform. But you should set a proper parameter, namely `logfc` in the function `findmarkergenes` because by default we take the log10 normalized data matrix as the input and set the fold change as `10^0.25 (log10fc = 0.25)` same as Seurat.
